public class OpportunityContactRoleData {
/*@AuraEnabled
    public static List<OpportunityContactRole> getContactList(List<Id> accountIds) {
        // Getting the list of contacts from where Id is in accountIds
 //               List<OpportunityContactRole> contactList = [SELECT Id, FirstName, LastName FROM Contact WHERE AccountId in :accountIds];
                // Returning the contact list
        return contactList;
    }*/
}